-- OwnStack MVP Supabase hardening
-- Run this in the Supabase SQL editor before demo/deploy if these columns or policies do not exist yet.

alter table public.profiles
  add column if not exists bio text,
  add column if not exists nostr_npub text;

alter table public.invoices
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists owner_pubkey text,
  add column if not exists lightning_address text,
  add column if not exists local_amount numeric,
  add column if not exists currency text default 'NGN',
  add column if not exists sats_amount numeric,
  add column if not exists payment_method text default 'bank_transfer';

create table if not exists public.vault_documents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  owner_pubkey text,
  title text not null,
  document_type text default 'receipt',
  file_name text,
  file_path text,
  file_url text,
  note text,
  amount numeric,
  currency text default 'NGN',
  created_at timestamptz default now()
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vault',
  'vault',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.invoices enable row level security;
alter table public.vault_documents enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can read own profile'
  ) then
    create policy "Users can read own profile"
      on public.profiles for select
      using (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'profiles' and policyname = 'Users can upsert own profile'
  ) then
    create policy "Users can upsert own profile"
      on public.profiles for all
      using (auth.uid() = id)
      with check (auth.uid() = id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'invoices' and policyname = 'Users can manage own invoices'
  ) then
    create policy "Users can manage own invoices"
      on public.invoices for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'invoices' and policyname = 'Public can read shared invoices'
  ) then
    create policy "Public can read shared invoices"
      on public.invoices for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'vault_documents' and policyname = 'Users can manage own vault documents'
  ) then
    create policy "Users can manage own vault documents"
      on public.vault_documents for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can read own vault files'
  ) then
    create policy "Users can read own vault files"
      on storage.objects for select
      using (bucket_id = 'vault' and auth.uid()::text = (storage.foldername(name))[1]);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can upload own vault files'
  ) then
    create policy "Users can upload own vault files"
      on storage.objects for insert
      with check (bucket_id = 'vault' and auth.uid()::text = (storage.foldername(name))[1]);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can update own vault files'
  ) then
    create policy "Users can update own vault files"
      on storage.objects for update
      using (bucket_id = 'vault' and auth.uid()::text = (storage.foldername(name))[1])
      with check (bucket_id = 'vault' and auth.uid()::text = (storage.foldername(name))[1]);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'Users can delete own vault files'
  ) then
    create policy "Users can delete own vault files"
      on storage.objects for delete
      using (bucket_id = 'vault' and auth.uid()::text = (storage.foldername(name))[1]);
  end if;
end $$;
