"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabase";
import InvoicePreview from "@/components/InvoicePreview";
import Link from "next/link";

export default function PublicInvoicePage() {
  const params = useParams();
  const id = params.id;
  const [invoice, setInvoice] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [profile, setProfile] = useState<any>(null);

  useEffect(() => {
    if (id) {
      fetchInvoice();
    }
  }, [id]);

  // Automated polling for payment status
  useEffect(() => {
    if (!invoice || invoice.status === "Paid" || invoice.status === "Completed") return;

    const interval = setInterval(() => {
      fetchInvoice();
    }, 5000); // Check every 5 seconds

    return () => clearInterval(interval);
  }, [invoice?.status, id]);

  async function fetchInvoice() {
    // We only set loading true for the first fetch to avoid flickering
    if (!invoice) setLoading(true); 
    
    try {
      const { data, error } = await supabase
        .from("invoices")
        .select("*")
        .eq("id", id)
        .single();

      if (error) throw error;
      setInvoice(data);

      // Fetch the creator's profile for the lightning address
      if (data.user_id && !profile) {
        const { data: profileData } = await supabase
          .from("profiles")
          .select("*")
          .eq("id", data.user_id)
          .single();
        if (profileData) setProfile(profileData);
      }
    } catch (err) {
      console.error("Error fetching public invoice:", err);
    } finally {
      if (loading) {
        // Small artificial delay for premium feel on first load
        setTimeout(() => setLoading(false), 800);
      }
    }
  }

  async function handleSettled() {
    if (!id) return;
    try {
      const { error } = await supabase
        .from("invoices")
        .update({ status: "Paid" })
        .eq("id", id);
      
      if (error) throw error;
      // Refresh local state
      fetchInvoice();
    } catch (err) {
      console.error("Failed to update settlement:", err);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#F8FAFC] flex flex-col items-center justify-center p-6">
        <div className="w-16 h-16 border-4 border-lime-200 border-t-lime-500 rounded-full animate-spin"></div>
        <p className="mt-6 text-slate-400 font-medium animate-pulse">Loading secure invoice...</p>
      </div>
    );
  }

  if (!invoice) {
    return (
      <div className="min-h-screen bg-[#F8FAFC] flex flex-col items-center justify-center p-6 text-center">
        <h1 className="text-4xl font-black text-[#0F172A]">404</h1>
        <p className="text-slate-500 mt-4 text-lg">We couldn't find that invoice.</p>
        <Link href="/" className="mt-8 bg-black text-white px-8 py-4 rounded-3xl font-bold">
          Go Home
        </Link>
      </div>
    );
  }

  return (
    <main className="min-h-screen bg-slate-50 flex flex-col items-center p-6 md:p-12">
      
      <div className="max-w-4xl w-full">
        
        {/* BRANDING */}
        <div className="flex items-center gap-2 mb-12 justify-center md:justify-start">
          <div className="w-8 h-8 rounded-lg bg-lime-400 text-black flex items-center justify-center font-bold">₿</div>
          <span className="text-xl font-black text-[#0F172A]">OwnStack</span>
        </div>

        <div className="grid lg:grid-cols-5 gap-12">
          
          <div className="lg:col-span-3">
            <h1 className="text-4xl font-black text-[#0F172A] leading-tight">
              Invoice for {invoice.customer}
            </h1>
            <p className="text-slate-500 text-lg mt-4 leading-relaxed">
              This invoice was generated by <strong>{profile?.business_name || "a verified merchant"}</strong> via OwnStack.
            </p>

            <div className="mt-12 p-8 bg-white rounded-[32px] border border-slate-100 shadow-sm relative overflow-hidden">
               <div className="absolute top-0 right-0 w-32 h-32 bg-lime-400/5 rounded-full -m-16"></div>
               <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest">Transaction Details</h3>
                  <div className={`px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider ${invoice.status === "Paid" || invoice.status === "Completed" ? "bg-lime-100 text-lime-700" : "bg-yellow-100 text-yellow-700"}`}>
                    {invoice.status}
                  </div>
               </div>
               <div className="mt-6 space-y-4">
                  <div className="flex justify-between border-b border-slate-50 pb-4">
                    <span className="text-slate-500">Service</span>
                    <span className="font-bold text-[#0F172A]">{invoice.service}</span>
                  </div>
                  <div className="flex justify-between border-b border-slate-50 pb-4">
                    <span className="text-slate-500">Amount</span>
                    <span className="font-bold text-lime-600 font-mono">{Number(invoice.amount).toLocaleString()} sats</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-500">Date</span>
                    <span className="font-bold text-[#0F172A]">{new Date(invoice.created_at).toLocaleDateString()}</span>
                  </div>
               </div>
            </div>

            <div className="mt-8 flex flex-col sm:flex-row gap-4">
              <button 
                onClick={fetchInvoice}
                disabled={loading}
                className="flex-1 bg-black hover:bg-slate-800 text-white px-8 py-5 rounded-[24px] font-bold transition active:scale-95 flex items-center justify-center gap-3 shadow-xl shadow-slate-200"
              >
                {loading ? <div className="w-5 h-5 border-2 border-white/20 border-t-white rounded-full animate-spin"></div> : "Check Payment Status"}
              </button>
              
              <div className="flex-[1.5] flex items-center gap-3 p-4 bg-lime-50 rounded-[24px] border border-lime-100">
                 <span className="w-10 h-10 bg-lime-400 rounded-xl flex items-center justify-center text-lg shadow-sm">🛡️</span>
                 <p className="text-xs text-lime-800 font-semibold leading-relaxed">Payments are verified on-chain. Status updates usually take 1-10 minutes.</p>
              </div>
            </div>
          </div>

          <div className="lg:col-span-2">
            <InvoicePreview 
               invoiceData={{
                 customer: invoice.customer,
                 service: invoice.service,
                 amount: invoice.amount
               }}
               lightningAddress={profile?.lightning_username}
               status={invoice.status}
               onSettled={handleSettled}
            />
          </div>

        </div>

      </div>

    </main>
  );
}
